# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from pymarketstore.proto import marketstore_pb2 as pymarketstore_dot_proto_dot_marketstore__pb2


class MarketstoreStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Query = channel.unary_unary(
        '/proto.Marketstore/Query',
        request_serializer=pymarketstore_dot_proto_dot_marketstore__pb2.MultiQueryRequest.SerializeToString,
        response_deserializer=pymarketstore_dot_proto_dot_marketstore__pb2.MultiQueryResponse.FromString,
        )
    self.Write = channel.unary_unary(
        '/proto.Marketstore/Write',
        request_serializer=pymarketstore_dot_proto_dot_marketstore__pb2.MultiWriteRequest.SerializeToString,
        response_deserializer=pymarketstore_dot_proto_dot_marketstore__pb2.MultiServerResponse.FromString,
        )
    self.Destroy = channel.unary_unary(
        '/proto.Marketstore/Destroy',
        request_serializer=pymarketstore_dot_proto_dot_marketstore__pb2.MultiKeyRequest.SerializeToString,
        response_deserializer=pymarketstore_dot_proto_dot_marketstore__pb2.MultiServerResponse.FromString,
        )
    self.ListSymbols = channel.unary_unary(
        '/proto.Marketstore/ListSymbols',
        request_serializer=pymarketstore_dot_proto_dot_marketstore__pb2.ListSymbolsRequest.SerializeToString,
        response_deserializer=pymarketstore_dot_proto_dot_marketstore__pb2.ListSymbolsResponse.FromString,
        )
    self.ServerVersion = channel.unary_unary(
        '/proto.Marketstore/ServerVersion',
        request_serializer=pymarketstore_dot_proto_dot_marketstore__pb2.ServerVersionRequest.SerializeToString,
        response_deserializer=pymarketstore_dot_proto_dot_marketstore__pb2.ServerVersionResponse.FromString,
        )


class MarketstoreServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Query(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Write(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Destroy(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListSymbols(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ServerVersion(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MarketstoreServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Query': grpc.unary_unary_rpc_method_handler(
          servicer.Query,
          request_deserializer=pymarketstore_dot_proto_dot_marketstore__pb2.MultiQueryRequest.FromString,
          response_serializer=pymarketstore_dot_proto_dot_marketstore__pb2.MultiQueryResponse.SerializeToString,
      ),
      'Write': grpc.unary_unary_rpc_method_handler(
          servicer.Write,
          request_deserializer=pymarketstore_dot_proto_dot_marketstore__pb2.MultiWriteRequest.FromString,
          response_serializer=pymarketstore_dot_proto_dot_marketstore__pb2.MultiServerResponse.SerializeToString,
      ),
      'Destroy': grpc.unary_unary_rpc_method_handler(
          servicer.Destroy,
          request_deserializer=pymarketstore_dot_proto_dot_marketstore__pb2.MultiKeyRequest.FromString,
          response_serializer=pymarketstore_dot_proto_dot_marketstore__pb2.MultiServerResponse.SerializeToString,
      ),
      'ListSymbols': grpc.unary_unary_rpc_method_handler(
          servicer.ListSymbols,
          request_deserializer=pymarketstore_dot_proto_dot_marketstore__pb2.ListSymbolsRequest.FromString,
          response_serializer=pymarketstore_dot_proto_dot_marketstore__pb2.ListSymbolsResponse.SerializeToString,
      ),
      'ServerVersion': grpc.unary_unary_rpc_method_handler(
          servicer.ServerVersion,
          request_deserializer=pymarketstore_dot_proto_dot_marketstore__pb2.ServerVersionRequest.FromString,
          response_serializer=pymarketstore_dot_proto_dot_marketstore__pb2.ServerVersionResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'proto.Marketstore', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
